### ISSUE TITLE
Setup Kanban 💪

### ISSUE THREAD

**Issue by leehaney254** [leehaney254/tutors-appointment-backend#19]
## In this project we were 4 :
- @leehaney254 
- @tanveerisonline 
- @codehass 
- @Josphat205 
## The image to our kanban board
![kanban ](https://user-images.githubusercontent.com/65546920/236225001-f59ed58b-f65d-4f3c-945d-7fa725a8a0d4.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- All issues have descriptions 👍 
- All issues are distributed equitably among team members 👍 
- Screenshot and info can be seen from this issue description 👍 

## Optional suggestions
- [OPTIONAL] Consider adding labels to make it easier to filter by and classify issues in the project board. [OPTIONAL]

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leehaney254** [comment]
Thank you @mcrd25  💪
